

export type AdaptiveModalClampingKeys = 
  | 'modalSizeHeight'
  | 'modalSizeWidth'
  | 'modalOriginX'
  | 'modalOriginY'
  | 'modalPaddingTop'
  | 'modalPaddingLeft'
  | 'modalPaddingBottom'
  | 'modalPaddingRight'
  | 'modalTransformTranslateX'
  | 'modalTransformTranslateY'
  | 'modalTransformTranslateZ'
  | 'modalTransformScaleX'
  | 'modalTransformScaleY'
  | 'modalTransformRotateX'
  | 'modalTransformRotateY'
  | 'modalTransformRotateZ'
  | 'modalTransformPerspective'
  | 'modalTransformSkewX'
  | 'modalTransformSkewY'
  | 'modalBorderWidth'
  | 'modalShadowOffset'
  | 'modalShadowRadius'
  | 'modalCornerRadius'
  | 'modalDragHandleSizeHeight'
  | 'modalDragHandleSizeWidth'
  | 'modalDragHandleOffset'
  | 'modalDragHandleCornerRadius';